name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
      - name: Build and test
        run: xcodebuild -scheme EssentialFeed -destination 'platform=iOS Simulator,name=iPhone 15' test

