name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode 16.4
        run: sudo xcode-select -s "/Applications/Xcode_16.4.app"

      - name: Build and Test
        run: xcodebuild clean build test \
              -project EssentialFeed.xcodeproj \
              -scheme "CI" \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGN_REQUIRED=NO
